# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sans Souci Group
email: hello@sanssoucigroup.com
description: > # this means to ignore newlines until "baseurl:"
  Sans Souci provides flexible, part-time business operations services to 
  small businesses, start-ups and self-employed individuals, who want things 
  to run more efficiently so they can focus on the needs of their business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sanssoucigroup.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
